name: 'Code Quality Check - `main` Branch'

on:
  push:
    branches:
      - main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Lint code
        run: npm run lint


      - name: Run tests
        run: npm run test
